> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestKotlin NO-SOURCE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :javadoc NO-SOURCE
> Task :javadocJar UP-TO-DATE
> Task :sourcesJar UP-TO-DATE
> Task :assemble UP-TO-DATE
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :check UP-TO-DATE
> Task :build UP-TO-DATE
> Task :aws-advanced-jdbc-wrapper:preprocessVersion UP-TO-DATE
> Task :aws-advanced-jdbc-wrapper:compileJava
> Task :aws-advanced-jdbc-wrapper:processResources
> Task :aws-advanced-jdbc-wrapper:classes
> Task :aws-advanced-jdbc-wrapper:jar
> Task :aws-advanced-jdbc-wrapper:javadoc
> Task :aws-advanced-jdbc-wrapper:javadocJar UP-TO-DATE

> Task :aws-advanced-jdbc-wrapper:sourcesJar
Execution optimizations have been disabled for task ':aws-advanced-jdbc-wrapper:sourcesJar' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/joycundy/rds/aug2022-aws-jdbc-wrapper/aws-advanced-jdbc-wrapper/wrapper/build/jcp/preprocessVersion'. Reason: Task ':aws-advanced-jdbc-wrapper:sourcesJar' uses this output of task ':aws-advanced-jdbc-wrapper:preprocessVersion' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :aws-advanced-jdbc-wrapper:assemble
> Task :aws-advanced-jdbc-wrapper:compileTestJava
> Task :aws-advanced-jdbc-wrapper:processTestResources UP-TO-DATE
> Task :aws-advanced-jdbc-wrapper:testClasses

> Task :aws-advanced-jdbc-wrapper:test
        [0;1m  2.8sec[0m, software.amazon.jdbc.[0;1mConnectionPluginManagerTests[0m > [0;1mtestConnectWithUnexpectedExceptionAfter()[0m

ConnectionPluginManagerTests > testConnectWithSQLExceptionAfter() STANDARD_ERROR
    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/Users/joycundy/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.36/a41f9cfe6faafb2eb83a1c7dd2d0dfd844e2a936/slf4j-simple-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/Users/joycundy/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.11/4741689214e9d1e8408b206506cbe76d1c6a7d60/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
          2.9sec,    8 completed,   0 failed,   0 skipped, software.amazon.jdbc.ConnectionPluginManagerTests
          0.6sec,   17 completed,   0 failed,   0 skipped, software.amazon.jdbc.PluginServiceImplTests
          0.7sec,    8 completed,   0 failed,   0 skipped, software.amazon.jdbc.hostlistprovider.AuroraHostListProviderTest

> Task :aws-advanced-jdbc-wrapper:checkstyleMain
> Task :aws-advanced-jdbc-wrapper:checkstyleTest

> Task :aws-advanced-jdbc-wrapper:test

AwsSecretsManagerConnectionPluginTest > testFailedInitialConnectionWithUnhandledError() STANDARD_ERROR
    [2022-09-02 14:17:38.444] [WARNING] software.amazon.jdbc.plugin.AwsSecretsManagerConnectionPlugin isLoginUnsuccessful
     Login failed. SQLState='HY000' 

AwsSecretsManagerConnectionPluginTest > testFailedToReadSecrets() STANDARD_ERROR
    [2022-09-02 14:17:38.456] [WARNING] software.amazon.jdbc.plugin.AwsSecretsManagerConnectionPlugin updateSecret
     Was not able to either fetch or read the database credentials from AWS Secrets Manager. Ensure the correct secretId and region properties have been provided. 

AwsSecretsManagerConnectionPluginTest > testConnectWithNewSecretsAfterTryingWithCachedSecrets(String) > software.amazon.jdbc.plugin.AwsSecretsManagerConnectionPluginTest.testConnectWithNewSecretsAfterTryingWithCachedSecrets(String)[1] STANDARD_ERROR
    [2022-09-02 14:17:38.533] [WARNING] software.amazon.jdbc.plugin.AwsSecretsManagerConnectionPlugin isLoginUnsuccessful
     Login failed. SQLState='28000' 

AwsSecretsManagerConnectionPluginTest > testConnectWithNewSecretsAfterTryingWithCachedSecrets(String) > software.amazon.jdbc.plugin.AwsSecretsManagerConnectionPluginTest.testConnectWithNewSecretsAfterTryingWithCachedSecrets(String)[2] STANDARD_ERROR
    [2022-09-02 14:17:38.545] [WARNING] software.amazon.jdbc.plugin.AwsSecretsManagerConnectionPlugin isLoginUnsuccessful
     Login failed. SQLState='28P01' 
          0.1sec,    2 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.[0;1mAwsSecretsManagerConnectionPluginTest[0m > [0;1mtestConnectWithNewSecretsAfterTryingWithCachedSecrets(String)[0m

AwsSecretsManagerConnectionPluginTest > testFailedToGetSecrets() STANDARD_ERROR
    [2022-09-02 14:17:38.557] [WARNING] software.amazon.jdbc.plugin.AwsSecretsManagerConnectionPlugin updateSecret
     Was not able to either fetch or read the database credentials from AWS Secrets Manager. Ensure the correct secretId and region properties have been provided. 
          1.4sec,    7 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.AwsSecretsManagerConnectionPluginTest
          0.0sec,    4 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.[0;1mDefaultConnectionPluginTest[0m > [0;1mtestCloseTransaction(String,[0m boolean)
          0.0sec,    7 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.[0;1mDefaultConnectionPluginTest[0m > [0;1mtestOpenTransaction(String,[0m boolean)
          0.0sec,    5 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.[0;1mDefaultConnectionPluginTest[0m > [0;1mtestParseMultiStatementQueries(String,[0m List)
          0.1sec,   16 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.DefaultConnectionPluginTest

IamAuthConnectionPluginTest > testMySqlConnectValidTokenInCache() STANDARD_ERROR
    [2022-09-02 14:17:38.638] [FINEST ] software.amazon.jdbc.plugin.IamAuthConnectionPlugin connect
     Use cached IAM token = 'testToken'. 

IamAuthConnectionPluginTest > testPostgresConnectValidTokenInCache() STANDARD_ERROR
    [2022-09-02 14:17:38.642] [FINEST ] software.amazon.jdbc.plugin.IamAuthConnectionPlugin connect
     Use cached IAM token = 'testToken'. 

IamAuthConnectionPluginTest > testConnectWithSpecifiedPort() STANDARD_ERROR
    [2022-09-02 14:17:38.644] [FINEST ] software.amazon.jdbc.plugin.IamAuthConnectionPlugin connect
     Use cached IAM token = 'testToken'. 

IamAuthConnectionPluginTest > testConnectWithSpecifiedRegion() STANDARD_ERROR
    [2022-09-02 14:17:38.648] [FINEST ] software.amazon.jdbc.plugin.IamAuthConnectionPlugin connect
     Use cached IAM token = 'testToken'. 

IamAuthConnectionPluginTest > testConnectEmptyCache() STANDARD_ERROR
    [2022-09-02 14:17:38.737] [FINEST ] software.amazon.jdbc.plugin.IamAuthConnectionPlugin connect
     Generated new IAM token = 'generatedToken' 

IamAuthConnectionPluginTest > testConnectExpiredTokenInCache() STANDARD_ERROR
    [2022-09-02 14:17:38.744] [FINEST ] software.amazon.jdbc.plugin.IamAuthConnectionPlugin connect
     Generated new IAM token = 'generatedToken' 
          0.1sec,    7 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.IamAuthConnectionPluginTest
[0;34;1mWARNING[0m   0.0sec,    2 completed,   0 failed, [0;34;1m  2[0m skipped, software.amazon.jdbc.plugin.efm.[0;34;1mConcurrencyTests[0m

HostMonitoringConnectionPluginTest > test_4_executeMonitoringEnabled() STANDARD_ERROR
    [2022-09-02 14:17:38.922] [FINEST ] software.amazon.jdbc.plugin.efm.HostMonitoringConnectionPlugin execute
     Executing method 'Connection.executeQuery', monitoring is activated 
    [2022-09-02 14:17:38.924] [FINEST ] software.amazon.jdbc.plugin.efm.HostMonitoringConnectionPlugin execute
     Executing method 'Connection.executeQuery', monitoring is activated 
          0.0sec,    3 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.efm.[0;1mHostMonitoringConnectionPluginTest[0m > [0;1mtest_1_initWithNullArguments(PluginService,[0m Properties)
          0.2sec,    6 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.efm.HostMonitoringConnectionPluginTest

MonitorConnectionContextTest > test_4_isNodeUnhealthyExceedsFailureDetectionCount() STANDARD_ERROR
    [2022-09-02 14:17:38.946] [FINEST ] software.amazon.jdbc.plugin.efm.MonitorConnectionContext setConnectionValid
     Host [any.node.domain] is not *responding* 1. 
    [2022-09-02 14:17:38.946] [FINEST ] software.amazon.jdbc.plugin.efm.MonitorConnectionContext setConnectionValid
     Host [any.node.domain] is not *responding* 2. 
    [2022-09-02 14:17:38.946] [FINEST ] software.amazon.jdbc.plugin.efm.MonitorConnectionContext setConnectionValid
     Host [any.node.domain] is not *responding* 3. 
    [2022-09-02 14:17:38.947] [FINEST ] software.amazon.jdbc.plugin.efm.MonitorConnectionContext setConnectionValid
     Host [any.node.domain] is not *responding* 4. 
    [2022-09-02 14:17:38.947] [FINEST ] software.amazon.jdbc.plugin.efm.MonitorConnectionContext setConnectionValid
     Host [any.node.domain] is not *responding* 5. 
    [2022-09-02 14:17:38.948] [FINE   ] software.amazon.jdbc.plugin.efm.MonitorConnectionContext setConnectionValid
     Host [any.node.domain] is *dead*. 

MonitorConnectionContextTest > test_3_isNodeUnhealthyExceedsFailureDetectionCount_returnTrue() STANDARD_ERROR
    [2022-09-02 14:17:38.949] [FINEST ] software.amazon.jdbc.plugin.efm.MonitorConnectionContext setConnectionValid
     Host [any.node.domain] is not *responding* 4. 

MonitorConnectionContextTest > test_2_isNodeUnhealthyWithInvalidConnection_returnFalse() STANDARD_ERROR
    [2022-09-02 14:17:38.950] [FINEST ] software.amazon.jdbc.plugin.efm.MonitorConnectionContext setConnectionValid
     Host [any.node.domain] is not *responding* 1. 

MonitorConnectionContextTest > test_1_isNodeUnhealthyWithConnection_returnFalse() STANDARD_ERROR
    [2022-09-02 14:17:38.951] [FINEST ] software.amazon.jdbc.plugin.efm.MonitorConnectionContext setConnectionValid
     Host [any.node.domain] is *alive*. 
          0.0sec,    4 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.efm.MonitorConnectionContextTest
         42.4sec, 1000 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.efm.[0;1mMonitorImplTest[0m > [0;1mtest_9_runWithContext()[0m
         42.4sec, 1008 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.efm.MonitorImplTest

MonitorServiceImplTest > test_8_startMonitoringNoNodeKeys() STANDARD_ERROR
    [2022-09-02 14:18:21.701] [WARNING] software.amazon.jdbc.plugin.efm.MonitorServiceImpl startMonitoring
     Empty alias set passed for hostSpec. Set should not be empty. 
          0.3sec,    9 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.efm.MonitorServiceImplTest
          1.1sec, 1000 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.efm.[0;1mMultiThreadedDefaultMonitorServiceTest[0m > [0;1mtest_4_stopMonitoring_multipleConnectionsToTheSameNode()[0m
          1.0sec, 1000 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.efm.[0;1mMultiThreadedDefaultMonitorServiceTest[0m > [0;1mtest_3_stopMonitoring_multipleConnectionsToDifferentNodes()[0m
          1.1sec, 1000 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.efm.[0;1mMultiThreadedDefaultMonitorServiceTest[0m > [0;1mtest_1_startMonitoring_multipleConnectionsToDifferentNodes()[0m
          1.0sec, 1000 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.efm.[0;1mMultiThreadedDefaultMonitorServiceTest[0m > [0;1mtest_2_startMonitoring_multipleConnectionsToOneNode()[0m
          4.1sec, 4000 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.efm.MultiThreadedDefaultMonitorServiceTest

ClusterAwareReaderFailoverHandlerTest > testFailover_timeout() STANDARD_ERROR
    [2022-09-02 14:18:25.818] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'reader3:1234/' 
    [2022-09-02 14:18:25.818] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'reader5:1234/' 
        [0;1m  5.0sec[0m, software.amazon.jdbc.plugin.failover.[0;1mClusterAwareReaderFailoverHandlerTest[0m > [0;1mtestFailover_timeout()[0m

ClusterAwareReaderFailoverHandlerTest > testGetReader_connectionAttemptsTimeout() STANDARD_ERROR
    [2022-09-02 14:18:30.818] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'reader1:1234/' 
    [2022-09-02 14:18:30.819] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'reader2:1234/' 
        [0;1m  3.0sec[0m, software.amazon.jdbc.plugin.failover.[0;1mClusterAwareReaderFailoverHandlerTest[0m > [0;1mtestGetReader_connectionAttemptsTimeout()[0m

ClusterAwareReaderFailoverHandlerTest > testGetReader_connectionSuccess() STANDARD_ERROR
    [2022-09-02 14:18:33.829] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Connected to reader 'reader1:1234/' 
    [2022-09-02 14:18:33.829] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Connected to reader 'reader2:1234/' 
    [2022-09-02 14:18:33.830] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'reader2:1234/' 
    [2022-09-02 14:18:33.830] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'reader1:1234/' 
    [2022-09-02 14:18:33.831] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Connected to reader 'reader2:1234/' 

ClusterAwareReaderFailoverHandlerTest > testGetReader_connectionFailure() STANDARD_ERROR
    [2022-09-02 14:18:33.833] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'reader2:1234/' 
    [2022-09-02 14:18:33.833] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'reader3:1234/' 
    [2022-09-02 14:18:33.834] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Failed to connect to reader 'reader2:1234/' 
    [2022-09-02 14:18:33.835] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Failed to connect to reader 'reader3:1234/' 
    [2022-09-02 14:18:34.841] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'reader1:1234/' 
    [2022-09-02 14:18:34.842] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Failed to connect to reader 'reader1:1234/' 
        [0;1m  2.0sec[0m, software.amazon.jdbc.plugin.failover.[0;1mClusterAwareReaderFailoverHandlerTest[0m > [0;1mtestGetReader_connectionFailure()[0m

ClusterAwareReaderFailoverHandlerTest > testFailover_nullOrEmptyHostList() STANDARD_ERROR
    [2022-09-02 14:18:35.849] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler failover
     'failover' was called with an invalid (null or empty) topology 
    [2022-09-02 14:18:35.850] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler failover
     'failover' was called with an invalid (null or empty) topology 

ClusterAwareReaderFailoverHandlerTest > testFailover() STANDARD_ERROR
    [2022-09-02 14:18:35.852] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'reader1:1234/' 
    [2022-09-02 14:18:35.852] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'reader3:1234/' 
    [2022-09-02 14:18:35.853] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Failed to connect to reader 'reader1:1234/' 
    [2022-09-02 14:18:35.853] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Failed to connect to reader 'reader3:1234/' 
    [2022-09-02 14:18:36.854] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'reader5:1234/' 
    [2022-09-02 14:18:36.854] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'writer:1234/' 
    [2022-09-02 14:18:36.855] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Failed to connect to reader 'reader5:1234/' 
    [2022-09-02 14:18:36.856] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Failed to connect to reader 'writer:1234/' 
    [2022-09-02 14:18:37.861] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'reader4:1234/' 
    [2022-09-02 14:18:37.861] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Trying to connect to reader 'reader2:1234/' 
    [2022-09-02 14:18:37.862] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Connected to reader 'reader4:1234/' 
    [2022-09-02 14:18:37.863] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call
     Failed to connect to reader 'reader2:1234/' 
        [0;1m  2.0sec[0m, software.amazon.jdbc.plugin.failover.[0;1mClusterAwareReaderFailoverHandlerTest[0m > [0;1mtestFailover()[0m
         12.1sec,    8 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandlerTest

ClusterAwareWriterFailoverHandlerTest > testConnectToReaderA_taskADefers() STANDARD_ERROR
    [2022-09-02 14:18:37.936] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$ReconnectToWriterHandler call
     [TaskA] Attempting to re-connect to the current writer instance: 'writer-host/' 
    [2022-09-02 14:18:37.937] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler call
     [TaskB] Attempting to connect to a new writer instance 
    [2022-09-02 14:18:37.938] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$ReconnectToWriterHandler call
     [TaskA] Finished 
    [2022-09-02 14:18:37.938] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler connectToReader
     [TaskB] Connected to reader 'reader-a-host/' 
    [2022-09-02 14:18:37.939] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler logTopology
     [TaskB] Topology obtained: 
       [0]: new-writer-host
       [1]: writer-host
       [2]: reader-a-host
       [3]: reader-b-host 
    [2022-09-02 14:18:37.939] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler connectToWriter
     [TaskB] Trying to connect to a new writer 'new-writer-host/' 
    [2022-09-02 14:18:42.941] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler call
     [TaskB] Finished 
    [2022-09-02 14:18:42.942] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler logTaskSuccess
     Successfully connected to the new writer instance: 'new-writer-host/' 
        [0;1m  5.1sec[0m, software.amazon.jdbc.plugin.failover.[0;1mClusterAwareWriterFailoverHandlerTest[0m > [0;1mtestConnectToReaderA_taskADefers()[0m

ClusterAwareWriterFailoverHandlerTest > testReconnectToWriter_SlowReaderA() STANDARD_ERROR
    [2022-09-02 14:18:42.947] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$ReconnectToWriterHandler call
     [TaskA] Attempting to re-connect to the current writer instance: 'writer-host/' 
    [2022-09-02 14:18:42.947] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler call
     [TaskB] Attempting to connect to a new writer instance 
    [2022-09-02 14:18:42.948] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$ReconnectToWriterHandler call
     [TaskA] Finished 
    [2022-09-02 14:18:42.949] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler call
     [TaskB] Finished 
    [2022-09-02 14:18:42.949] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler logTaskSuccess
     Successfully re-connected to the current writer instance: 'writer-host/' 

ClusterAwareWriterFailoverHandlerTest > testFailedToConnect_taskAException_taskBWriterException() STANDARD_ERROR
    [2022-09-02 14:18:42.956] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$ReconnectToWriterHandler call
     [TaskA] Attempting to re-connect to the current writer instance: 'writer-host/' 
    [2022-09-02 14:18:42.956] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler call
     [TaskB] Attempting to connect to a new writer instance 
    [2022-09-02 14:18:42.957] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler connectToReader
     [TaskB] Connected to reader 'reader-a-host/' 
    [2022-09-02 14:18:42.957] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler logTopology
     [TaskB] Topology obtained: 
       [0]: new-writer-host
       [1]: reader-a-host
       [2]: reader-b-host 
    [2022-09-02 14:18:42.958] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler connectToWriter
     [TaskB] Trying to connect to a new writer 'new-writer-host/' 
    [2022-09-02 14:18:44.960] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler logTopology
     [TaskB] Topology obtained: 
       [0]: new-writer-host
       [1]: reader-a-host
       [2]: reader-b-host 
    [2022-09-02 14:18:44.960] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler connectToWriter
     [TaskB] Trying to connect to a new writer 'new-writer-host/' 
    [2022-09-02 14:18:46.961] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler logTopology
     [TaskB] Topology obtained: 
       [0]: new-writer-host
       [1]: reader-a-host
       [2]: reader-b-host 
    [2022-09-02 14:18:46.962] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler connectToWriter
     [TaskB] Trying to connect to a new writer 'new-writer-host/' 
    [2022-09-02 14:18:48.967] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler logTopology
     [TaskB] Topology obtained: 
       [0]: new-writer-host
       [1]: reader-a-host
       [2]: reader-b-host 
    [2022-09-02 14:18:48.967] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler connectToWriter
     [TaskB] Trying to connect to a new writer 'new-writer-host/' 
    [2022-09-02 14:18:50.969] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler logTopology
     [TaskB] Topology obtained: 
       [0]: new-writer-host
       [1]: reader-a-host
       [2]: reader-b-host 
    [2022-09-02 14:18:50.970] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler connectToWriter
     [TaskB] Trying to connect to a new writer 'new-writer-host/' 
    [2022-09-02 14:18:52.965] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler failover
     Failed to connect to the writer instance. 
    [2022-09-02 14:18:52.966] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$ReconnectToWriterHandler call
     [TaskA] Finished 
    [2022-09-02 14:18:52.966] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler call
     [TaskB] Finished 
        [0;1m 10.0sec[0m, software.amazon.jdbc.plugin.failover.[0;1mClusterAwareWriterFailoverHandlerTest[0m > [0;1mtestFailedToConnect_taskAException_taskBWriterException()[0m

ClusterAwareWriterFailoverHandlerTest > testFailedToConnect_failoverTimeout() STANDARD_ERROR
    [2022-09-02 14:18:52.969] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$ReconnectToWriterHandler call
     [TaskA] Attempting to re-connect to the current writer instance: 'writer-host/' 
    [2022-09-02 14:18:52.969] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler call
     [TaskB] Attempting to connect to a new writer instance 
    [2022-09-02 14:18:52.970] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler connectToReader
     [TaskB] Connected to reader 'reader-a-host/' 
    [2022-09-02 14:18:52.970] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler logTopology
     [TaskB] Topology obtained: 
       [0]: new-writer-host
       [1]: reader-a-host
       [2]: reader-b-host 
    [2022-09-02 14:18:52.970] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler connectToWriter
     [TaskB] Trying to connect to a new writer 'new-writer-host/' 
    [2022-09-02 14:19:02.976] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler failover
     Failed to connect to the writer instance. 
    [2022-09-02 14:19:02.977] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$ReconnectToWriterHandler call
     [TaskA] Finished 
        [0;1m 10.0sec[0m, software.amazon.jdbc.plugin.failover.[0;1mClusterAwareWriterFailoverHandlerTest[0m > [0;1mtestFailedToConnect_failoverTimeout()[0m

ClusterAwareWriterFailoverHandlerTest STANDARD_ERROR
    [2022-09-02 14:19:02.977] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler call
     [TaskB] Finished 

ClusterAwareWriterFailoverHandlerTest > testReconnectToWriter_taskBReaderException() STANDARD_ERROR
    [2022-09-02 14:19:02.979] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$ReconnectToWriterHandler call
     [TaskA] Attempting to re-connect to the current writer instance: 'writer-host/' 
    [2022-09-02 14:19:02.979] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler call
     [TaskB] Attempting to connect to a new writer instance 
    [2022-09-02 14:19:02.980] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$ReconnectToWriterHandler call
     [TaskA] Finished 
    [2022-09-02 14:19:02.980] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler logTaskSuccess
     Successfully re-connected to the current writer instance: 'writer-host/' 
    [2022-09-02 14:19:02.980] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler connectToReader
     [TaskB] Failed to connect to any reader. 
    [2022-09-02 14:19:02.980] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler call
     [TaskB] Finished 

ClusterAwareWriterFailoverHandlerTest > testReconnectToWriter_taskBDefers() STANDARD_ERROR
    [2022-09-02 14:19:02.982] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$ReconnectToWriterHandler call
     [TaskA] Attempting to re-connect to the current writer instance: 'writer-host/' 
    [2022-09-02 14:19:02.982] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler call
     [TaskB] Attempting to connect to a new writer instance 
    [2022-09-02 14:19:02.983] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler connectToReader
     [TaskB] Connected to reader 'reader-a-host/' 
    [2022-09-02 14:19:07.984] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$ReconnectToWriterHandler call
     [TaskA] Finished 
    [2022-09-02 14:19:07.985] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler logTaskSuccess
     Successfully re-connected to the current writer instance: 'writer-host/' 
    [2022-09-02 14:19:07.985] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler call
     [TaskB] Finished 
        [0;1m  5.0sec[0m, software.amazon.jdbc.plugin.failover.[0;1mClusterAwareWriterFailoverHandlerTest[0m > [0;1mtestReconnectToWriter_taskBDefers()[0m

ClusterAwareWriterFailoverHandlerTest > testConnectToReaderA_SlowWriter() STANDARD_ERROR
    [2022-09-02 14:19:07.988] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$ReconnectToWriterHandler call
     [TaskA] Attempting to re-connect to the current writer instance: 'writer-host/' 
    [2022-09-02 14:19:07.988] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler call
     [TaskB] Attempting to connect to a new writer instance 
    [2022-09-02 14:19:07.988] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler connectToReader
     [TaskB] Connected to reader 'reader-a-host/' 
    [2022-09-02 14:19:07.989] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler logTopology
     [TaskB] Topology obtained: 
       [0]: new-writer-host
       [1]: reader-a-host
       [2]: reader-b-host 
    [2022-09-02 14:19:07.989] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler connectToWriter
     [TaskB] Trying to connect to a new writer 'new-writer-host/' 
    [2022-09-02 14:19:07.989] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$WaitForNewWriterHandler call
     [TaskB] Finished 
    [2022-09-02 14:19:07.989] [FINE   ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler logTaskSuccess
     Successfully connected to the new writer instance: 'new-writer-host/' 
    [2022-09-02 14:19:07.989] [FINER  ] software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandler$ReconnectToWriterHandler call
     [TaskA] Finished 
         30.1sec,    7 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.failover.ClusterAwareWriterFailoverHandlerTest

FailoverConnectionPluginTest > test_failover_failoverReader() STANDARD_ERROR
    [2022-09-02 14:19:08.262] [INFO   ] software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin failover
     Transaction resolution unknown. Please re-configure session state if required and try restarting the transaction. 

FailoverConnectionPluginTest > test_failover_failoverWriter() STANDARD_ERROR
    [2022-09-02 14:19:08.274] [SEVERE ] software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin failover
     The active SQL connection has changed due to a connection failure. Please re-configure session state if required. 

FailoverConnectionPluginTest > test_failoverWriter_successFailover() STANDARD_ERROR
    [2022-09-02 14:19:08.277] [FINE   ] software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin failoverWriter
     Starting writer failover procedure. 
    [2022-09-02 14:19:08.278] [SEVERE ] software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin processFailoverFailure
     Unable to establish SQL connection to the writer instance 

FailoverConnectionPluginTest > test_failoverReader_withVNoFailedHostSpec_withException() STANDARD_ERROR
    [2022-09-02 14:19:08.281] [FINE   ] software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin failoverReader
     Starting reader failover procedure. 

FailoverConnectionPluginTest > test_failoverWriter_failedFailover_withNoResult() STANDARD_ERROR
    [2022-09-02 14:19:08.285] [FINE   ] software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin failoverWriter
     Starting writer failover procedure. 
    [2022-09-02 14:19:08.286] [SEVERE ] software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin processFailoverFailure
     Unable to establish SQL connection to the writer instance 
          0.0sec,    2 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.failover.[0;1mFailoverConnectionPluginTest[0m > [0;1mtest_updateTopology_withForceUpdate(boolean)[0m

FailoverConnectionPluginTest > test_failoverReader_withValidFailedHostSpec_successFailover() STANDARD_ERROR
    [2022-09-02 14:19:08.294] [FINE   ] software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin failoverReader
     Starting reader failover procedure. 
    [2022-09-02 14:19:08.294] [FINE   ] software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin failoverReader
     Connected to: mockHostSpec 

FailoverConnectionPluginTest > test_failoverWriter_failedFailover_throwsException() STANDARD_ERROR
    [2022-09-02 14:19:08.302] [FINE   ] software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin failoverWriter
     Starting writer failover procedure. 

FailoverConnectionPluginTest > test_notifyNodeListChanged_withValidConnectionNotInTopology() STANDARD_ERROR
    [2022-09-02 14:19:08.304] [FINEST ] software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin notifyNodeListChanged
     Changes:
    Host 'instance/': [NODE_ADDED]
    Host 'cluster-host/': [NODE_DELETED] 
          0.3sec,   23 completed,   0 failed,   0 skipped, software.amazon.jdbc.plugin.failover.FailoverConnectionPluginTest
          0.0sec,    8 completed,   0 failed,   0 skipped, software.amazon.jdbc.util.[0;1mConnectionUrlParserTest[0m > [0;1mtestGetHostsFromConnectionUrl_returnCorrectHostList(String,[0m List)
          0.0sec,    8 completed,   0 failed,   0 skipped, software.amazon.jdbc.util.ConnectionUrlParserTest
          0.0sec,    6 completed,   0 failed,   0 skipped, software.amazon.jdbc.util.RdsUtilsTests
        [0;1m 15.1sec[0m, software.amazon.jdbc.util.[0;1mWrapperUtilsTest[0m > [0;1mtestExecutesWithPluginsWithExceptionIsSequential()[0m
        [0;1m 15.0sec[0m, software.amazon.jdbc.util.[0;1mWrapperUtilsTest[0m > [0;1mtestExecutesWithPluginsIsSequential()[0m
         30.1sec,    2 completed,   0 failed,   0 skipped, software.amazon.jdbc.util.WrapperUtilsTest
[0;34;1mWARNING[0m 127.8sec, 5146 completed,   0 failed, [0;34;1m  2[0m skipped, [0;34;1mGradle Test Run :aws-advanced-jdbc-wrapper:test[0m

> Task :aws-advanced-jdbc-wrapper:jacocoTestCoverageVerification

> Task :aws-advanced-jdbc-wrapper:spotbugsMain
SpotBugs ended with exit code 1

> Task :aws-advanced-jdbc-wrapper:spotbugsTest
SpotBugs ended with exit code 1

> Task :aws-advanced-jdbc-wrapper:check
> Task :aws-advanced-jdbc-wrapper:build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD SUCCESSFUL in 2m 30s
24 actionable tasks: 12 executed, 12 up-to-date
